### PR TITLE
Depend on all packages < 1.0.0, bump to 0.7.5

### PR DESCRIPTION
**Pull request by mostalive**
Changed all dependencies to use '^' instead of '>=', so bower does not
go searching for 1.0.0 packages and their dependencies.

Also bumped version to 0.7.5, so this can go on to bower soon,
hopefully.

(I finally read:
https://github.com/npm/node-semverhttps://github.com/npm/node-semver
).

It looks like the build (and a local install) failed because one of our
dependencies' dependencies does not yet exist in the right version.

Separate minor version, so things that depend on this (two of my
packages) that can't yet be upgraded because not all their (transitive)
dependencies exist in the right version yet.

I guess upgrading to all 1.0.0+ dependencies should be done in a version
of purescript-spec that is also 1.0.0?

### CODE REVIEW

**Comment by mostalive** [comment]
Travis failures was:
bower resolved      https://github.com/purescript/purescript-math.git#0.2.0

bower ECONFLICT     Unable to find suitable version for purescript-exceptions

The command "bower install" failed and exited with 1 during .

Your build has been stopped.

**Comment by mostalive** [comment]
:-( More build errors, on travis I don't know how to fix this one (related to npm install).

Suggestions?

quoting travis:
$ npm install

npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.

> bufferutil@1.2.1 install /home/travis/build/mostalive/purescript-firebase/node_modules/bufferutil

> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

make: Entering directory `/home/travis/build/mostalive/purescript-firebase/node_modules/bufferutil/build'

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

In file included from ../src/bufferutil.cc:16:0:

../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler

In file included from ../src/bufferutil.cc:7:0:

/home/travis/.node-gyp/6.1.0/include/node/v8.h:341:1: error: expected unqualified-id before ‘using’

/home/travis/.node-gyp/6.1.0/include/node/v8.h:477:1: error: expected unqualified-id before ‘using’

/home/travis/.node-gyp/6.1.0/include/node/v8.h:871:1: error: expected unqualified-id before ‘using’

In file included from ../../nan/nan.h:196:0,

                 from ../src/bufferutil.cc:16:

**Comment by mostalive** [comment]
Seems there is a problem with purescript on node 6, it might work on node 5. just came across this:

https://github.com/alexmingoia/pux-starter-app/issues/18

**Comment by owickstrom** [comment]
Thanks for reporting! I'll take a look at this ASAP. Been away on vacation, sorry for the delay.

**Comment by mostalive** [comment]
No worries!

I noticed there are some other branches in the network (without pull
requests it seems, I didn't have time to look into it so far) working on
similar things, there is one with a similar version fix, and another
long-running branch with travis changes, which might be useful to fix the
NPM version.

Thanks for looking in to it, I hope you had a great holiday!

**Comment by owickstrom** [comment]
As many packages are moving to 1.0.0 and PureScript 0.9.1 is out I bumped our dependency versions to 1.0.0, which works well with PureScript 0.9.1 now.

As for the Node 5/6 thing, it seems there's nothing we can do here to fix it.

Thank you for the pull request!
